server:
    port: 8050
    session:
        cookie:
            name: UISESSION
            
spring:
    application:
        name: zuul-edge
    security:
      oauth2:
        client:
          registration:
            custom-client:
              client-id: R2dpxQ3vPrtfgF72
              client-secret: fDw7Mpkk5czHNuSRtmhGmAGL42CaxQB9
              client-name: Auth Server
              scope: user_info
              provider: custom-provider
              redirect-uri: http://localhost:8050/login/oauth2/code/
              client-authentication-method: basic
              authorization-grant-type: authorization_code
          provider:
            custom-provider:
              token-uri: http://localhost:8080/auth/oauth/token
              authorization-uri: http://localhost:8080/auth/oauth/authorize
              user-info-uri: http://localhost:8080/auth/user/me
              user-name-attribute: name        

zuul:
    routes:
      hellos:
          path: /hello
          url: http://localhost:8082/
      limits:
          path: /limits
          url: http://localhost:8081/